### ISSUE TITLE
organization and packaging

### ISSUE THREAD

**Issue by lheagy** [marcoalopez/GrainSizeTools#2]
This is related to the JOSS pre-review issue: openjournals/joss-reviews#811

The package layout does not follow standard python packaging practices (see for example: https://packaging.python.org/tutorials/packaging-projects/). 
```
/grain_size_tools  # repo
   /grain_size_tools  # python module
       __init__.py  # contains import to be brought in when the user runs import grain_size_tools
       tools.py
       piezometers.py
       ...
```

This would allow more flexible use - for example if a user wants to install your package through pypi and import it into a Jupyter notebook as a part of their workflow. 

The main items to be addressed are: 
- [x] folder structure and inclusion of `__init__.py` files (this allows `from grain_size_tools import piezometers` for example) - a good resource on why these are used is here: https://docs.python.org/3/tutorial/modules.html#packages
- [x] setup.py for installing (this way the user can run `python setup.py install` from the repository-level directory to install the package - https://packaging.python.org/tutorials/packaging-projects/
- [ ] (optional): you can deploy your package to pypi so that instead of someone having to download the GitHub repository and running the setup.py, they can run `pip install grain_size_tools` from a command line and it performs the download and install: https://packaging.python.org/tutorials/packaging-projects/

Please let me know if there are more resources I can send along that would be helpful!

**Comment by marcoalopez** [comment]
I'm a little stuck at this point. I have created the necessary structure including the ``setup.py`` and ``__init__.py`` files. I am able to import the whole package, for example using ``import grain_size_tools as gst`` or some module, for example ``from grain_size_tools import piezometers``. However, I cannot import the modules which in turn import other modules from within the file. For example, the ``plots.py`` file calls the ``tools.py`` file using ``from tools import gen_xgrid, log_function``, so when using for example ``from grain_size_tools import plots`` I get the following error: ``ModuleNotFoundError: No module named 'tools'``.

To explain in a nutshell how I organized the script:

- ``GrainSizeTools.py`` contains the functions that the user will interact with. This module calls all other modules ``piezometers.py``, ``tools.py``, and ``plots.py``
- ``Pizometers.py`` contains a list of all the experimentally-derived values of the different piezometers
- ``tools.py`` contains a number of functions used by the script. The intention is that the normal user does not interact directly with these functions. This module calls the ``plots.py`` module
- ``plots.py`` contains all the functions related to the plots. This module calls the ``tools.py`` module

**Comment by lheagy** [comment]
Hi @marcoalopez: sorry for my late reply here. For users, if they run `python setup.py install` this moves the package contents to the site-packages and then `grain_size_tools` will be in their namespace. You should also be able to do this on your machine.  

However, if you make changes to the package, you need to re-run the setup.py to again move the packages over. For development, this can be a bit tedious, and you might want python to look at the version in a `git` folder. We have a bit of documentation on setting up a development environment here: http://docs.simpeg.xyz/content/basic/getting_started_developers.html#setting-up-your-environment. 

The `sys.path.append` workaround is fine for the submission too.

**Comment by jsta** [comment]
Chiming in here rather than starting a new issue because my comment is related to installation. 

Should the `python setup.py install` line be added to the [Getting Started](https://github.com/marcoalopez/GrainSizeTools/blob/master/DOCS/brief_tutorial.md) page? 

Also, I find it a little strange that `setup.py` is located in the top folder (containing the paper) rather than in the same folder as `GrainSizeTool_script.py`.

**Comment by marcoalopez** [comment]
Hi @jsta, I plan to do this in the future since as stated above I will add the package to pypi when the revision ends. So far the documentation only describes how to use the script by manually downloading it from the repositories and running it in the Spyder or Canopy IDEs.

Regarding the ``setup.py`` file, I located it in the top folder of the repository following these guides:
https://packaging.python.org/tutorials/packaging-projects/
https://docs.python-guide.org/writing/structure/
So I guess it's the most common way to do it (although I'm not completely sure since I'm not an expert on these matters)

**Comment by jsta** [comment]
You are correct about the location of `setup.py`. I'm still learning these things myself.
