### ISSUE TITLE
Dependency list

### ISSUE THREAD

**Issue by jsta** [marcoalopez/GrainSizeTools#3]
This issue is related to the ongoing JOSS review of this package. One of the criteria is:

**Installation instructions:** Is there a clearly-stated list of dependencies? Ideally these should be handled with an automated package management solution.

However, I found myself struggling to easily find the dependency list to get started. What do you think about adding a `requirements.txt` or `environment.yml` file?

**Comment by jsta** [comment]
I this a complete list of dependencies?

```
numpy
pandas
scipy
matplotlib
tkinter
```

I am having trouble installing `tkinter` using `conda`.

**Comment by marcoalopez** [comment]
Hello @jsta, Tkinter is Python's de-facto standard GUI so I think it is not necessary to install it using conda or pip since it should be already available on Unix platforms as well as on Windows systems when installing Python (isn't that right?). I will add a ``requirements.txt`` file with the dependencies.

**Comment by marcoalopez** [comment]
I already added the ``requirements.txt`` file
